"""
Django settings for skripsi_rekomendasi project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vjkx(qvc^j33-&qyem&in0rw!x3*a15jnwo@(fslmf=bu7%lih'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web_rekomendasi'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skripsi_rekomendasi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skripsi_rekomendasi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_rekomendasi_umkm',
        'USER': 'root',      # Default user Laragon
        'PASSWORD': '',      # Default password Laragon biasanya kosong
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
# --- KONFIGURASI REDIRECT LOGIN/LOGOUT ---

# Setelah berhasil login, arahkan ke halaman dengan nama 'dashboard'
LOGIN_REDIRECT_URL = 'dashboard'

# Setelah logout, arahkan kembali ke halaman login (atau dashboard)
LOGOUT_REDIRECT_URL = 'login'

# Halaman login ada di URL mana? (Django perlu tahu ini untuk @login_required)
LOGIN_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ... (Ini kode bawaan Django di bagian atas, biarkan saja) ...
# STATIC_URL = 'static/'
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# PASTE KODE INI DI SINI (PALING BAWAH FILE)
# ==========================================

JAZZMIN_SETTINGS = {
    # Judul di Tab Browser
    "site_title": "Admin UMKMGo",

    # Judul di Halaman Login & Dashboard
    "site_header": "UMKMGo Dashboard",
    "site_brand": "UMKMGo",

    # Pesan Selamat Datang
    "welcome_sign": "Selamat Datang di Panel Admin UMKMGo",
    "copyright": "UMKMGo Skripsi 2026",

    # Menu Pencarian
    "search_model": ["web_rekomendasi.Produk", "auth.User"],

    # Custom Menu Atas
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Lihat Website", "url": "/", "new_window": True},
    ],

    # Menu User (Pojok Kanan Atas)
    "usermenu_links": [
        {"model": "auth.user"}
    ],

    # Tampilkan Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Ikon Menu (FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "web_rekomendasi.Produk": "fas fa-box-open",
        "web_rekomendasi.Penilaian": "fas fa-star",
        "web_rekomendasi.PreferensiPengguna": "fas fa-heart",
    },
    
    # Urutan Menu
    "order_with_respect_to": ["web_rekomendasi", "auth"],
}

# TEMA TAMPILAN (HIJAU GOJEK)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-success",
    "sidebar_nav_small_text": False,
    "theme": "flatly", 
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
