# Generated by Django 6.0 on 2026-01-30 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_rekomendasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='no_telepon',
        ),
        migrations.AddField(
            model_name='umkm',
            name='no_whatsapp',
            field=models.CharField(default='628xxxxx', help_text='Format: 628xxx (Tanpa +)', max_length=20),
        ),
        migrations.AddField(
            model_name='umkm',
            name='pemilik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toko', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
